version: '3.8'

networks:
  zen_test:

services:
  web:
    build:
      context: .
      dockerfile: .docker/web/Dockerfile
    container_name: zen_web
    restart: always
    ports:
      - 8000:8000
    networks:
      - zen_test
    depends_on:
      - db
    volumes:
      - ./web:/usr/src/app

  db:
    image: mariadb
    container_name: zen_db
    restart: always
    volumes:
      - .docker/db/volume:/var/lib/mysql
    networks:
      - zen_test
    env_file: .docker/db/.env
